# Generated by Django 4.2.3 on 2024-09-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('DF', 'Черновик'), ('PB', 'Опубликован')], default='DF', max_length=2, verbose_name='Статус'),
        ),
    ]
